name: Deploy
on:
  workflow_call:
    inputs:
      stage:
        description: "The stage to deploy to"
        required: true
        type: string
      dry-run:
        type: boolean
        required: false
        default: false

    secrets:
      SF_SERVER_KEY:
        description: "The private key used by SF to grant access to this pipeline"
        required: true
      SF_CONSUMER_KEY:
        description: "The SF connected app key"
        required: true

env:
  SERVICE_NAME: external-sf-poc
  NODE_VERSION: 18
  SLACK_CHANNEL: independents-monitor

jobs:
  deploy:
    if: |
      inputs.stage == 'sandbox' ||
      inputs.stage == 'prd'

    environment:
      name: ${{ inputs.stage }}

    runs-on:
      - self-hosted
      - independents-nonprod-deploy

    concurrency:
      group: deploy-${{ inputs.stage }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install Dependencies
        run: npm install

      - name: Authenticate with Salesforce
        env:
          SFDX_INTEGRATION_URL: ${{ secrets.SFDX_INTEGRATION_URL }}
        run: |
          echo $SFDX_INTEGRATION_URL > auth-url.txt
          sf org login sfdx-url --sfdx-url-file auth-url.txt --alias DevOrg --set-default

      - name: Deploy to Salesforce
        run: npx sf project deploy preview --manifest changes/package/package.xml --post-destructive-changes changes/destructiveChanges/destructiveChanges.xml  -o ${{ vars.SF_USERNAME }}