name: Deploy Salesforce Code to Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    env:
      RED_TEXT: '\033[0;31m'
      GREEN_TEXT: '\033[0;32m'
      BLUE_TEXT: '\033[0;34m'
      YELLOW_TEXT: '\033[1;33m'
      RESET_TEXT: '\033[0m'
      FORCE_APP_FOLDER: force-app
      DEPLOY_FOLDER: deployFolder
      NODE_VERSION : '6.14.18'

    steps:

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Install Salesforce CLI'
        run: |
                   wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
                   mkdir ~/sf
                   tar xJf sf-linux-x64.tar.xz -C ~/sf --strip-components 1
                   echo "$HOME/sf/bin" >> $GITHUB_PATH
                   ~/sf/bin/sf version
                   ~/sf/bin/sf plugins install @salesforce/sfdx-scanner
                   echo y | ~/sf/bin/sf plugins install sfdx-git-delta

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout target
        run: |
              git fetch origin ${{ github.base_ref }} --depth 1

      - name: Generate Delta
        run: mkdir ${{ env.DEPLOY_FOLDER }} && npx sf sgd:source:delta --to HEAD --from origin/${{ github.base_ref }} --output ${{ env.DEPLOY_FOLDER }} --generate-delta

      - name: Authenticate with Salesforce
        env:
          SFDX_INTEGRATION_URL: ${{ secrets.SFDX_INTEGRATION_URL }}
        run: |
          echo $SFDX_INTEGRATION_URL > auth-url.txt
          sf org login sfdx-url --sfdx-url-file auth-url.txt --alias DeployOrg --set-default

      - name: Deploy to Salesforce
        run:  |
          echo $(cat  ${{ env.DEPLOY_FOLDER }}/package/package.xml )
          sf project deploy preview --manifest ${{ env.DEPLOY_FOLDER }}/package/package.xml 
      
      - name: Run Tests
        run: |
          sf apex run test --target-org DeployOrg --result-format tap --output-dir test-results --wait 10

      - name: Display Test Results
        run: cat test-results/test-result.tap
