name: PR to Develop

on:
  pull_request:
    branches:
      - develop1

jobs:
  ci:
    uses: ./.github/workflows/_test.yaml
    with:
      stage: sandbox

  delta:
    needs: ci
    uses: ./.github/workflows/_delta.yaml
    with:
      stage: sandbox